### ISSUE TITLE
大佬能封装为Android的APP程序吗？

### ISSUE THREAD

**Issue by guyingd** [kosaka-bun/qqrobot-farm#3]

**Comment by kosaka-bun** [comment]
本项目需要连接数据库服务，在Android平台上不适用，故暂不考虑支持。

**Comment by guyingd** [comment]
其实可以手机用termux运行，但比较麻烦，所以提问能不能封装Android的APP

**Comment by guyingd** [comment]
毕竟大部分都机器人程序支持多平台运行，据我了解部分人还是喜欢用Android版机器人，这样不会局限在部分系统平台

**Comment by guyingd** [comment]
大佬有QQ群吗？我想加群

**Comment by kosaka-bun** [comment]
非常感谢你的支持，请关注我的bilibili账号：https://space.bilibili.com/37089492
粉丝群在其动态当中。
